<?xml version="1.0" encoding="shift-jis"?>
<!DOCTYPE option [
	<!ELEMENT option (dialog+)>
	<!ELEMENT dialog (item*)>
	<!ELEMENT item (#PCDATA)>
	<!ATTLIST dialog id CDATA #REQUIRED>
	<!ATTLIST dialog description CDATA #IMPLIED>
	<!ATTLIST item id CDATA #REQUIRED>
	<!ATTLIST item caption CDATA #IMPLIED>
	<!ENTITY lt "&#38;#60;">
	<!ENTITY gt "&#62;">
	<!ENTITY amp "&#38;#38;">
	<!ENTITY apos "&#39;">
	<!ENTITY quot "&#34;">
]>
<option>
	<dialog id="204" description="全般">
		<item id="1027" caption="お気に入りやファイルを新しいウィンドウで開く">
			お気に入りやファイルを開く際に新しいタブで開くかどうかを設定します。
			OFFにした場合はアクティブなタブで開くようにします。
			
			※お気に入りはIEと共有ですが拡張プロパティの設定をすることでセキュリティ
			　 やマルチメディア、unDonutの設定を個別に指定して開くことが出来ます。
			　 お気に入りの右クリックメニューから拡張プロパティを開き設定をします。
		</item>
		<item id="1026" caption="お気に入りやファイルを開くとき、アクティブにしない">
			新しいタブが開かれたときにそのタブをアクティブにするかどうかを設定します。
			ONにするとアクティブなタブはそのままに新しいタブが開かれます。
		</item>
		<item id="1058" caption="リンクを開くときアクティブにしない">
			ページ内のリンクをクリックして新しいタブを開いたときにそのタブをアクティブにするかどうかを設定します。
			ONにするとアクティブなタブはそのままに新しいタブが開かれます。
		</item>
		<item id="1041" caption="お気に入りグループを開くとき、他のウィンドウを閉じない">
			お気に入りグループを開く際にそれまで開かれていたタブの扱いを設定します。
			OFFにするとそれまでのタブは全て閉じられます。
		</item>
		<item id="1065" caption="お気に入りの追加に、コモンダイアログを使う">
			お気に入りを追加する際にIE標準の専用ダイアログを用いるか、
			ファイル保存用のコモンダイアログを使用するか設定します。
		</item>
		<item id="1066" caption="お気に入りの整理に、エクスプローラを使う">
			お気に入りの整理をする際にIE標準の専用ダイアログを使うか、
			エクスプローラで直接ファイルを操作するか設定します。
		</item>
		<item id="1115" caption="リンクのターゲット名を考慮する">
			フレームページのリンクを開く際、フレームの指定に従うかどうかを設定します。
			ONにした場合リンクの表示先を指定されたフレームにし、新しいタブで開く設定は無視されます。
		</item>
		<item id="1029" caption="複数起動を許可しない">
			アプリケーションの多重起動を許可するかどうか設定します。
			ONにした場合2つ目以降の起動はキャンセルされます。
		</item>
		<item id="1048" caption="タブモードで起動する">
			タブを常に最大化した状態で表示するかを設定します。
			ONにするとMDIウィンドウとしての操作はできなくなりますが、
			タブ切り替え時のちらつきがなくなります。
		</item>
		<item id="1034" caption="ウィンドウの数を制限する">
			開くことができる最大のタブ数を設定します。
		</item>
		<item id="1052" caption="状態をDefault.dfgへ定期的に保存する">
			開いているタブの状態を定期的に保存するかどうか設定します。
			分単位での間隔設定ができます。
			OFFにするとunDonut終了時にタブの状態を保存します。
			[ファイル]-[新規作成]の「Default.dfg」やコマンドの「Default.dfg」で
			保存された状態を再現して開くことが出来ます。
		</item>
		<item id="1104" caption="オン/オフラインの状態を保存する">
			ファイルメニューのオフライン設定を次回起動時に復元するかどうかを設定します。
			ONにすると設定は保存し持ち越されます。
		</item>
		<item id="1106" caption="警告ダイアログを自動的に閉じる">
			警告ダイアログが出た場合、マウスでクリックすることなく自動的に閉じます。
			セキュリティの警告等、一部のダイアログは表示自体を行いません。
		</item>
    <item id="1117" caption="ブラウザのオプションを継承する">
			リンクを新しいページで開く時、マルチメディア・セキュリティ等の状態を継承します。
		</item>
		<item id="1055" caption="自動更新 分">
			ページの自動更新を任意の時間に設定します。
			実行の際は[表示]-[自動更新]-[○秒(ユーザー設定)]にチェックします。
		</item>
		<item id="1057" caption="自動更新 秒">
			ページの自動更新を任意の時間に設定します。
			実行の際は[表示]-[自動更新]-[○秒(ユーザー設定)]にチェックします。
		</item>
		<item id="1126" caption="フォント">
			各バーのフォントを変更します。フォントを変更する場合は書体の
			種類が「日本語」になっていないと文字化けすることがあります。
		</item>
	</dialog>
	
	<dialog id="247" description="全般2">
		<item id="1155" caption="メニューバー表示">
		全画面表示にしたとき表示される各バーを選択します。
		※デフォルトではタイトルバー、タスクバーも非表示になり、ブラウザウィンドウのみが表示されます。
		　 全画面表示を使用しなくても、うっかり全画面表示にした時に元に戻せずに困る場合があるので
		　 「メニューバー表示」にチェックを入れておくことをお勧めします。
		</item>
		<item id="1156" caption="標準のボタン表示">
			
		</item>
		<item id="1157" caption="リンクバー表示">
			
		</item>
		<item id="1158" caption="タブバー表示">
			
		</item>
		<item id="1159" caption="検索バー表示">
			
		</item>
		<item id="1160" caption="アドレスバー表示">
			
		</item>
		<item id="1161" caption="ステータスバー表示">
			
		</item>
		<item id="1154" caption="第一領域サイズ">
			更新状況を表示する読込ゲージの大きさを設定します。
			0にすると表示されなくなります。
		</item>
		<item id="1134" caption="第二領域サイズ">
			プロキシを表示するプロキシ切り替えの大きさを設定します。
			0にすると表示されなくなります。
		</item>
		<item id="1163" caption="読み込みゲージとプロキシ切り替えの配置場所を入れ換える">
			読み込みゲージとプロキシ切り替えの位置を入れ替えます。
			※読み込みゲージとプロキシ切り替えの位置を交換すると、
			　第一領域サイズがプロキシ切り替えの大きさに第二領域
			　サイズが読込ゲージの大きさにそれぞれ反映されます。
		</item>
		<item id="1249" caption="お気に入りグループに適用">
			前に戻る・次へ進むの履歴をお気に入りグループに保存し、
			展開する時に再現して開きます。
		</item>
		<item id="1250" caption="最近閉じたページに適用">
			[ファイル]-[最近閉じたファイル]を開く時、前に戻る・次へ進むの
			履歴を再現して開きます。
		</item>
		<item id="1255" caption="項目の最大数">
			[ファイル]-[最近閉じたファイル]の保存数を設定します。
		</item>
		<item id="1254" caption="項目の表示方法">
			[ファイル]-[最近閉じたファイル]の表示方法を設定します。
		</item>
		<item id="1320" caption="しない">
			最小化ボタン、閉じるボタンはともに通常の動作をします。
		</item>
		<item id="1321" caption="最小化ボタン">
			最小化ボタンを押した時に、最小化せずにタスクトレイのアイコン状態にします。
		</item>
		<item id="1322" caption="閉じるボタン">
			閉じるボタンを押した時に、終了せずにタスクトレイのアイコン状態にします。
		</item>
	</dialog>
	
	<dialog id="230" description="ツールバー">
		<item id="1131" caption="カテゴリ">
			登録するコマンドのカテゴリを選択します。
		</item>
		<item id="1133" caption="コマンド">
			登録するコマンドを選択します。
		</item>
		<item id="1144" caption="アイコン・リスト">
			※このリストには[Donutのオプション]-[スキン]で指定したスキンの「BigHot.bmp」の
			　 アイコン(画像)が表示され、そのアイコンにコマンドを割り当てます。
			　 コマンドの登録数分だけアイコンを表示するので、全てのアイコンが表示されない場合は
			　 適当にコマンドを追加することで表示されます。
			
			　 ツールバーに表示するアイコンの編集する場合は[表示]-[ツールバー]-[ユーザー設定]で
			　 変更します。
		</item>
		<item id="1145" caption="追加">
			選択したコマンドをリストの最後尾に追加します。
		</item>
		<item id="1146" caption="←">
			リストで選択したコマンドを左に移動します。
			※コマンドの削除や挿入をすると使用出来ます。
		</item>
		<item id="1147" caption="→">
			リストで選択したコマンドを右に移動します。
			※コマンドの削除や挿入をすると使用出来ます。
		</item>
		<item id="1148" caption="削除">
			リストで選択したコマンドを削除します。
			※後ろのコマンドが左に1つずつスライドして、アイコンとずれるので
			　 気を付けてください。
		</item>
		<item id="1152" caption="挿入">
			リストで選択した位置にコマンドを挿入します。
			コマンドを指定しリストで挿入するアイコンを選択てください。
			※後ろのコマンドが右に1つずつスライドして、アイコンとずれるので
			　 気を付けてください。
		</item>
		<item id="1082" caption="右側テキスト表示">
			アイコンの右側にコマンド名を表示します。
		</item>
	</dialog>
	
	<dialog id="103" description="タブバー">
		<item id="1088" caption="追加位置">
			新しくウィンドウを開いた時にタブの追加位置の選択を行います。
		</item>
		<item id="1092" caption="アクティブなタブを閉じた時">
			アクティブなタブを閉じた時どのタブをアクティブにするのかを選択します。
			※MDI標準を指定すると一つ前にアクティブだったタブに戻ります。
		</item>
		<item id="1204" caption="リンクを開くときはアクティブの右側へ追加">
			リンクを新しいウィンドウで開く時はアクティブなタブの右側へ追加します。
		</item>
		<item id="1089" caption="右クリック">
			タブ上でマウスを右クリックした場合の動作を選択します。
		</item>
		<item id="1090" caption="ダブルクリック">
			タブ上でマウスをダブルクリック(左)した場合の動作を選択します。
		</item>
		<item id="1091" caption="ホイールクリック">
			タブ上でマウスをホイールクリックした場合の動作を選択します。
		</item>
		<item id="1083" caption="マウスホイールで切り替え">
			タブ上でホイールを回転させた場合にタブの切り替えを行います。
		</item>
		<item id="1050" caption="複数列表示にする">
			タブを複数列にわたって表示します。
		</item>
		<item id="1084" caption="タブの大きさを指定する">
			タブの大きさを指定します。
			設定すると大きさは固定されます。
		</item>
		<item id="1085" caption="タブの大きさ 幅">
			タブの幅を指定します。
		</item>
		<item id="1086" caption="タブの大きさ 高さ">
			タブの高さを指定します。
		</item>
		<item id="1016" caption="タブの最大文字数">
			タブのタブの最大文字数を指定します。
		</item>
		<item id="1109" caption="未表示./表示済みを色分けする">
			タブに表示される文字の色分けを行います。
			※ユーザーが任意の色を指定出来ます。
			　 tabskin.txtを参照してください。
		</item>
		<item id="1248" caption="マウス左ボタンを押したときにタブを切り替える">
			左ボタンを押し込んだ時にタブを切り替えるようにします。
			※デフォルトではボタンを離したときにタブを切り替えます。
		</item>
		<item id="1317" caption="CTRL(+SHIFT)+TABでの移動をMDIでの順番にする">
			CTRL+TAB,CTRL+SHIFT+TABでのタブ移動を、MDIでの順番にします。
			これを指定しない場合は、タブの並び順に移動します。
		</item>
	</dialog>

	<dialog id="107" description="アドレスバー">
		<item id="1060" caption="新しいウィンドウを開く">
			アドレスバーからサイトを開くとき新しいウィンドウで開きます。
		</item>
		<item id="1064" caption="新しいウィンドウを開くときアクティブにしない">
			アドレスバーからサイトを新しいウィンドウで開いた場合に当該ウィンドウをアクティブにしません。
		</item>
		<item id="1062" caption="オートコンプリートを有効にして起動(IE5以上)">
			入力補助機能が有効になります。
			有効にするとアドレスバーに入力した文字列で始まるアドレスの一覧がドロップダウンリストに表示されます。
		</item>
		<item id="1093" caption="IEの入力履歴の読み込みと保存を行う">
			アドレスバーに入力した文字列の履歴を保存します。IEと共用です。
			チェックを外すとunDonutのアドレスバーへの入力履歴は一切保存されません。
		</item>
		<item id="1094" caption="移動ボタンを表示する">
			アドレスバーの右端に移動ボタンを表示します。
		</item>
		<item id="1069" caption="文字を表示する">
			「アドレスバー」「検索バー」「リンクバー」各バーに名称を表示します。
		</item>
		<item id="1300" caption="">
			ブラウザのパスを指定すると、アドレスバーのアイコンをダブルクリックした時に
			アクティブなページのアドレスを指定したブラウザで開きます。
		</item>
		<item id="1151" caption="『Ctrl』＋『Enter』時">
			アドレスバーにフォーカスのある状態で実行すると、文字列を指定した検索エンジンに渡します。
		</item>
		<item id="1153" caption="『Shift』＋『Enter』時">
			アドレスバーにフォーカスのある状態で実行すると、文字列を指定した検索エンジンに渡します。
		</item>
		<item id="1215" caption="検索時に全角スペースを半角に置換する">
			検索を実行時に全角スペースを半角スペースに置換をします。
		</item>
		<item id="1241" caption="Ctrl+Enter">
			『Ctrl』＋『Enter』を実行時に適用する検索エンジンを指定します。
		</item>
		<item id="1242" caption="Shift+Enter">
			『Shift』＋『Enter』を実行時に適用する検索エンジンを指定します。
		</item>
	</dialog>

	<dialog id="249" description="検索バー">
		<item id="1274" caption="検索エンジン変更時に即検索">
			検索エンジン変更したらすぐに検索を開始します。
		</item>
		<item id="1275" caption="ドロップ時に即検索">
			検索バーに範囲選択した文字列やタブをドロップしたらすぐに検索を開始します。
		</item>
		<item id="1277" caption="検索履歴を保存する">
			WEB検索の履歴を保存します。
			※ページ内検索をしただけでは保存されません。
		</item>
		<item id="1278" caption="最大保存数">
			検索履歴を保存する最大数を指定します。
		</item>
		<item id="1279" caption="検索エンジンはみ出し防止動作をやめる（マルチモニタの人用）">
			検索エンジンはみ出し防止動作をやめます。
			※マルチモニタの人用です。
		</item>
		<item id="1280" caption="キーワード変更時に即検索">
			キーワード変更時にすぐに検索を開始します。
		</item>
		<item id="1207" caption="リストの最大表示項目数を指定する:">
			※リストの長さがモニタの解像度をオーバーすると正常に表示されません。
			　 画面に収まるように最大表示項目数を指定していしてください。
			　 検索エンジンリストがオーバーする場合はSearch.ini Editor等で
			　 不要な検索エンジンを削除しリストを縮めてください。
			　 Resorce HackerでunDonut.exeのリソースを書き換えることで表示領域を
			　 変更出来ます。
		</item>
		<item id="1239" caption="単語ボタンを使用しない">
			WEB検索をした時に生成されるページ内検索用の単語ボタンを非表示にします。
		</item>
		<item id="1315" caption="単語ボタン使用時にも単独のページ内検索ボタンを表示する">
			単語ボタンを使用している時にも単独のページ内検索ボタンを表示するようにします。
		</item>
		<item id="1208" caption="最大表示項目数">
			
		</item>
		<item id="1214" caption="全角スペースを半角とみなして検索する">
			検索時に全角スペースを半角スペースとみなして検索します。
		</item>
		<item id="1238" caption="最後に選択した検索エンジンを記憶する">
			終了時に選択した検索エンジンを次回起動時に表示します
		</item>
		<item id="1276" caption="検索結果が中央に来るようにスクロールする">
			ページ内検索でスクロールが可能な場合に、検索結果を中央に表示します。
		</item>
		<item id="1251" caption="検索結果はアクティブなウィンドウに表示する">
			検索結果をアクティブなウィンドウに表示します。
		</item>
		<item id="1257" caption="検索結果に対して自動的にハイライトを実行する">
			WEB検索実行時に自動的にハイライトを実行します。

			環境によってはunDonutが落ちる原因となります。
			不安定な場合はチェックを外してください。
		</item>
	</dialog>
	<dialog id="276" description="リンクバー">
		<item id="1306" caption="小さいアイコンを使う">
			リンクバーで小さいアイコンを使用します。
		</item>
		<item id="1307" caption="大きいアイコンを使う">
			リンクバーで大きいアイコンを使用します。
		</item>
		<item id="1308" caption="アイコンを表示しない">
			リンクバーでアイコンを非表示にします。
		</item>
		<item id="1309" caption="">
			リンクバーで使用するフォルダを指定します。
		</item>

	</dialog>

	<dialog id="235" description="エクスプローラバー">
		<item id="1101" caption="水平スクロールを使う(再起動後有効)">
			エクスプローラバーの字数が横幅をオーバーした時に
			水平方向のスクロールバーを表示します。
		</item>
		<item id="1107" caption="お気に入り時イメージを使う(再起動後有効)">
			エクスプローラバーにお気に入りを表示する際、独自アイコンを使います。
		</item>
		<item id="1105" caption="お気に入りの間隔詰める(再起動後有効)">
			エクスプローラバーのお気に入りやスクリプト等の間隔を詰めて表示します。
			※メニューのお気に入りの間隔を詰める場合は[Donutのオプション]-[お気に入りメニュー]の
			　 「間隔を詰める」をチェックします。
		</item>
		<item id="1259" caption="自動で表示する">
			カーソル位置により自動でエクスプローラバーを表示します。
		</item>
		<item id="1236" caption="ユーザー定義フォルダ">
			ユーザーが指定したフォルダを開きます。
			インターネット ショートカットを置いたフォルダを指定することで、
			独自ブックマークとして使えます。
			ユーザー定義をコマンドで表示する場合は[カテゴリ]-[表示]の「ユーザー」を使用します。
			※メニューバーの指定は[メニュー]-[お気に入りメニュー]-[ユーザー定義のフォルダ]
			　 で指定します。
		</item>
		<item id="1235" caption="...">
			
		</item>
	</dialog>

	<dialog id="250" description="メニュー">
		<item id="1181" caption="メニューの文字を編集しない（文字化けが起きる人用）">
			NT系でメニューの表示がおかしい場合にチェックします。
		</item>
		<item id="1162" caption="右クリックメニューをカスタムしない(新規窓より有効)">
			IE標準の右クリックメニューを使用します。
		</item>
		<item id="1218" caption="右クリックメニュー上の右クリックは左クリックと同じ動作にする">
			右クリックメニュー上の右クリックは左クリックと同じ動作にします。
		</item>
		<item id="1291" caption="最小化・最大化・閉じるボタンを表示しない（再起動後有効）">
			タブモードで起動していない時(MDIモード)に表示される
			MDIウィンドウ用のボタンを非表示にします。
		</item>
		<item id="1301" caption="日本語">
			メニューバーの項目を日本語で表示します。
		</item>
		<item id="1302" caption="1文字">
			メニューバーの項目をアルファベットの1文字で表示します。
		</item>
		<item id="1303" caption="英語">
			メニューバーの項目を英語で表示します。
			ポップアップメニューは日本語のままです。
		</item>
		<item id="1183" caption="対象">
			右クリックメニューの対象を選択します。
		</item>
		<item id="1131" caption="カテゴリ">
			登録するコマンドのカテゴリを選択します。
		</item>
		<item id="1133" caption="コマンド">
			登録するコマンドを選択します。
		</item>
		<item id="1190" caption="登録1">
			選択したコマンドを登録します。
		</item>
		<item id="1191" caption="削除1">
			選択したコマンドを削除します。
		</item>
		<item id="1192" caption="登録2">
			選択したコマンドを登録します。
		</item>
		<item id="1193" caption="削除2">
			選択したコマンドを削除します。
		</item>
		<item id="1178" caption="前方追加コマンド">
			メニュー上部にコマンドを追加します。
		</item>
		<item id="1179" caption="後方追加コマンド">
			メニュー下部にコマンドを追加します。
		</item>
		<item id="1185" caption="↑1">
			選択したコマンドを上方向に移動します。
		</item>
		<item id="1187" caption="↓1">
			選択したコマンドを下方向に移動します。
		</item>
		<item id="1189" caption="↑2">
			選択したコマンドを上方向に移動します。
		</item>
		<item id="1194" caption="↓2">
			選択したコマンドを下方向に移動します。
		</item>
	</dialog>

	<dialog id="206" description="お気に入りメニュー">
		<item id="1030" caption="「これらをすべて開く」という項目を追加する">
			メニューバーのお気に入りに「これらすべてを開く」というコマンドを追加します。
		</item>
		<item id="1067" caption="「この位置にお気に入り追加」という項目を追加する">
			メニューバーのお気に入りに「この位置にお気に入り追加」というコマンドを追加します。
		</item>
		<item id="1095" caption="IEの順番で並べる">
			IEのお気に入りを使用する場合にIEと同じ順で並べます。
		</item>
		<item id="1031" caption="メニューの最大文字数">
			表示される文字数の制限をします。
		</item>
		<item id="1033" caption="各段の最大項目数">
			各フォルダー単位で表示できる項目数を制限します。
			お気に入りの登録数が多くてスクロールが気になる場合は、
			モニタに収まるように最大項目数を設定し複数列で表示
			させると良いです。
		</item>
		<item id="1097" caption="ユーザー定義のフォルダ">
			ユーザーが指定したフォルダをお気に入りとして開きます。
			インターネット ショートカットを置いたフォルダを指定することで、
			独自ブックマークとして使えます。
			※リンクバーでユーザー定義のフォルダを指定する場合はnogui.txtを
			　 参照してください。
		</item>
		<item id="1098" caption="ユーザー定義のフォルダ・エディット">
			ユーザー定義で使用するフォルダを指定します。
			※エクスプローラバーの指定は[エクスプローラバー]-[ユーザー定義フォルダ]
			　 で指定します。
		</item>
		<item id="1099" caption="...">
			
		</item>
		<item id="1096" caption="アイコンを表示させる">
			メニューバーのお気に入りのアイコンを表示/非表示を選択します。
		</item>
		<item id="1103" caption="間隔を詰める">
			メニューバーのお気に入りの間隔を詰めて表示します。
			※エクスプローラバーのお気に入りの間隔を詰める場合は[Donutのオプション]
			　 -[エクスプローラバー]の「お気に入りの間隔詰める」をチェックします。
		</item>
		<item id="1252" caption="お気に入りの順番をドラッグして並べかえできるようにする">
			メニューバーのお気に入りをドラッグ＆ドロップで並び替え出来るようにします。
			※実験的な機能であることを理解した上で使用してください。
		</item>
		<item id="1253" caption="「並び順を初期化する」という項目を追加する">
			メニューバーのお気に入りに「並び順を初期化する」というコマンドを追加します。
			「お気に入りの順番をドラッグして並べかえできるようにする」で異常が出た場合に
			試してください。
		</item>
	</dialog>

	<dialog id="303" description="ユーザー定義">
		<item id="1258" caption="リスト">
			ユーザーが任意にファイルを開いたり、スクリプトを実行出来るランチャー機能の編集をします。
			並び替えはドラッグ＆ドロップで可能です。
			実行は「ツールバー」「マウスジェスチャー」等の[カテゴリ]-[特殊]から「ユーザー定義メニュー表示」
			を選ぶか、[カテゴリ]-[ユーザー定義メニュー]から個別に選びます。
			※スクリプトの実行はsetup.exeを実行し、COMサーバー機能をONにしてください。
		</item>
		<item id="1259" caption="実行するファイル">
			実行するファイルのパスを指定します。
		</item>
		<item id="1262" caption="ファイルに与える引数">
			コマンドラインオプションを指定します。
		</item>
		<item id="1263" caption="メニュー項目名">
			項目名を指定します。
		</item>
		<item id="1265" caption="普通の項目">
			ファイルを登録時に指定します。
		</item>
		<item id="1266" caption="親項目">
			サブメニューを登録時に指定します。
			「実行するファイル」「ファイルに与える引数」の項目は無視されます。
		</item>
		<item id="1267" caption="セパレータ">
			セパレータを登録時に指定します。
			「メニュー項目名」「実行するファイル」「ファイルに与える引数」の項目は無視されます。
		</item>
		<item id="1014" caption="追加">
			項目内容を新規に登録します。
		</item>
		<item id="1015" caption="更新">
			既存の項目内容を更新します。
		</item>
		<item id="1013" caption="削除">
			選択した項目を削除します。
		</item>
	</dialog>

	<dialog id="229" description="キー">
		<item id="1131" caption="カテゴリ">
			登録するコマンドのカテゴリを選択します。
		</item>
		<item id="1133" caption="コマンド">
			登録するコマンドを選択します。
		</item>
		<item id="1136" caption="現在のキー">
			既に入力されているショートカットキーを表示します。
		</item>
		<item id="1138" caption="新しいキー入力">
			新たにキーを入力します。
			※既にショートカットキーが割り当てられていた場合は「キーの上書きを許可する」
			　 にチェックを入れていないと上書きすることができません。
			※他のメニューで既にショートカットキーが割り振られていた場合は「キーの移行を許可する」に
			　 チェックを入れていないとショートカットキーを入れ替えることができません。
		</item>
		<item id="1139" caption="削除">
			割り振られているショートカットキーを削除します。
			「キーの上書きを許可する」や「キーの移行を許可する」にチェックを
			入れていない場合は削除してからでないとキーを割り当てできません。
		</item>
		<item id="1140" caption="割当">
			新たに入力したキーを割り当てます。
			「キーの上書きを許可する」や「キーの移行を許可する」にチェックを
			入れていない場合は削除してからでないとキーを割り当てできません。
		</item>
		<item id="1141" caption="既存コマンド">
			入力しようとしたショートカットキーが既に他のメニューに
			利用されている場合に利用されているメニューを表示します。
		</item>
		<item id="1142" caption="キーの上書きを許可する">
			新しいキーを上書きし割り当てることができます。
		</item>
		<item id="1143" caption="キーの移行を許可する">
			既に他のコマンドでショートカットキーが入力されている場合に
			キーを入れ替えることができます。
		</item>
		<item id="1169" caption="リスト">
			
		</item>
	</dialog>

	<dialog id="248" description="マウス">
		<item id="1167" caption="リンク上→中クリック">
			リンク上でホイールをクリックした時の動作を選択します。
		</item>
		<item id="1195" caption="サイドボタン１《">
			左サイドボタンをクリックした時のコマンドを指定します。
			※Windows2000以降のOSで対応しています。
		</item>
		<item id="1292" caption="サイドボタン１">
			
		</item>
		<item id="1196" caption="サイドボタン２《">
			右サイドボタンをクリックした時のコマンドを指定します。
			※Windows2000以降のOSで対応しています。
		</item>
		<item id="1293" caption="サイドボタン２">
			
		</item>
		<item id="1197" caption="左クリック《">
			右ボタンを押したまま左クリックをした時のコマンドを指定します。
			※空欄か仕切り線を選択すると「デフォルト」の指定が出来ます。
		</item>
		<item id="1294" caption="左クリック">
			
		</item>
		<item id="1198" caption="中クリック《">
			右ボタンを押したまま中クリックをした時のコマンドを指定します。
			※空欄か仕切り線を選択すると「デフォルト」の指定が出来ます。
		</item>
		<item id="1295" caption="中クリック">
			
		</item>
		<item id="1199" caption="ホイール・アップ《">
			右ボタンを押したままホイールを上に回した時の動作を選択します。
			※空欄か仕切り線を選択すると「デフォルト」の指定が出来ます。
		</item>
		<item id="1296" caption="ホイール・アップ">
			
		</item>
		<item id="1200" caption="ホイール・ダウン《">
			右ボタンを押したままホイールを下に回した時の動作を選択します。
			※空欄か仕切り線を選択すると「デフォルト」の指定が出来ます。
		</item>
		<item id="1297" caption="ホイール・ダウン">
			
		</item>
		<item id="1201" caption="サイド１クリック《">
			右ボタンを押したまま左サイドボタンを押した時のコマンドを指定します。
			※空欄か仕切り線を選択すると「デフォルト」の指定が出来ます。
			※Windows2000以降のOSで対応しています。
		</item>
		<item id="1298" caption="サイド１クリック">
			
		</item>
		<item id="1202" caption="サイド２クリック《">
			右ボタンを押したまま右サイドボタンを押した時のコマンドを指定します。
			※空欄か仕切り線を選択すると「デフォルト」の指定が出来ます。
			※Windows2000以降のOSで対応しています。
		</item>
		<item id="1299" caption="サイド２クリック">
			
		</item>
		<item id="1240" caption="ページ内ドラッグドロップ">
			ページ内でリンクや範囲選択した文字列を適当な位置に
			ドラッグ＆ドロップした時の動作をを指定します。
		</item>
		<item id="1204" caption="ウィンドウサイド・左端">
			ウィンドウ左端にカーソルを持っていった場合に実行するコマンドを指定します。
		</item>
		<item id="1203" caption="ウィンドウサイド・右端">
			ウィンドウ右端にカーソルを持っていった場合に実行するコマンドを指定します。
		</item>
		<item id="1205" caption="ウィンドウサイド・上端">
			ウィンドウ上端にカーソルを持っていった場合に実行するコマンドを指定します。
		</item>
		<item id="1206" caption="ウィンドウサイド・下端">
			ウィンドウ下端にカーソルを持っていった場合に実行するコマンドを指定します。
		</item>
	</dialog>

	<dialog id="290" description="マウスジェスチャー">
		<item id="1180" caption="↑">
			上方向のジェスチャーを入力します。
		</item>
		<item id="1182" caption="↓">
			下方向のジェスチャーを入力します。
		</item>
		<item id="1184" caption="←">
			左方向のジェスチャーを入力します。
		</item>
		<item id="1186" caption="→">
			右方向のジェスチャーを入力します。
		</item>
		<item id="1174" caption="C">
			入力中のジェスチャーをクリアします。
		</item>
		<item id="1131" caption="カテゴリ">
			登録するコマンドのカテゴリを選択します。
		</item>
		<item id="1133" caption="コマンド">
			登録するコマンドを選択します。
		</item>
		<item id="1141" caption="ジェスチャー">
			
		</item>
		<item id="1188" caption="リスト">
			※マウスジェスチャーは特定の動作をすることで指定したコマンドを実行します。
			　 例えば右ボタンを押したままマウスをL字を書くように動かすと、ボタンを離した時に
			　 「閉じる」実行します。(デフォルトの場合)
			　 使用する場合は[Donutのオプション]-[ブラウザ]の[マウス・ジェスチャーを使用する]を
			　 チェックしてください
		</item>
		<item id="1177" caption="登録">
			入力したジェスチャーを登録します。
		</item>
		<item id="1139" caption="削除">
			リストから選択した既存ジェスチャーを削除します。
		</item>
	</dialog>


	<dialog id="209" description="新規作成">
		<item id="1042" caption="空白ページを追加する">
			空白のページ(about:blank)を開きます。
		</item>
		<item id="1043" caption="現在のページを追加する">
			アクティブなページを開きます。
		</item>
		<item id="1044" caption="ホームページを追加する">
			[インターネットオプション]-[全般]の「ホーム ページ」で指定したアドレスを開きます。
		</item>
	</dialog>

	<dialog id="208" description="スタートアップ">
		<item id="1045" caption="何も開かない">
			unDonut起動時に何もページを開きません。
		</item>
		<item id="1036" caption="ホームページで開く">
			unDonut起動時に[インターネットオプション]-[全般]の「ホーム ページ」
			で指定したアドレスを開きます。
		</item>
		<item id="1037" caption="前回終了時の状態で開く">
			unDonut起動時に前回終了時の状態を再現して開きます。
		</item>
		<item id="1038" caption="お気に入りグループで開く">
			unDonut起動時に指定したお気に入りグループを開きます。
		</item>
		<item id="1039" caption="お気に入りグループ・エディット">
			unDonut起動時に開くお気に入りグループを指定します。
		</item>
		<item id="1040" caption="...">
			
		</item>
		<item id="1056" caption="関連付け起動時にDonutをアクティブにする">
			他ソフトやショートカット等、関連付けによりパスを渡された場合にunDonutを
			アクティブにします。
			他ソフトが関連付けを使わず、直接unDonutにパスを渡す場合は機能しません。
			ブラウザの指定で「標準」または空欄で試してください。
		</item>
		<item id="1112" caption="起動時にパラメータが渡された場合、起動処理は全て無効">
			関連付けによりunDonutが起動する場合はスタートアップで指定した処理を行いません。
		</item>
	</dialog>

	<dialog id="288" description="終了処理">
		<item id="1121" caption="キャッシュを削除する">
			unDonut終了時にインターネット一時ファイルを削除します。
		</item>
		<item id="1123" caption="Cookie を削除する">
			unDonut終了時にCookieを削除します。
		</item>
		<item id="1125" caption="履歴を消去する">
			unDonut終了時に履歴を削除します。
		</item>
		<item id="1081" caption="エクスプローラバーのキャッシュを作成する（お気に入り時）">
			unDonut終了時にエクスプローラバーのキャッシュ作成をします。
		</item>
		<item id="1223" caption="最近閉じたファイルの履歴を削除する">
			unDonut終了時に[ファイル]-[最近閉じたファイル]の履歴を削除します。
		</item>
	</dialog>

	<dialog id="104" description="ブラウザ">
		<item id="1018" caption="サウンドの再生">
			サウンドの再生を許可した状態でウィンドウを開きます。
		</item>
		<item id="1019" caption="ビデオの再生">
			ビデオの再生を許可した状態でウィンドウを開きます。
		</item>
		<item id="1025" caption="画像のダウンロード">
			画像の表示を許可した状態でウィンドウを開きます。
		</item>
		<item id="1022" caption="ActiveXコントロールの実行">
			ActiveXコントロールの実行を許可した状態でウィンドウを開きます。
		</item>
		<item id="1021" caption="ActiveXコントロールのダウンロード">
			ActiveXコントロールのダウンロードを許可した状態でウィンドウを開きます。
		</item>
		<item id="1023" caption="スクリプトの実行">
			JavaScriptの実行を許可した状態でウィンドウを開きます。
		</item>
		<item id="1024" caption="Javaの実行">
			Javaの実行を許可した状態でウィンドウを開きます。
		</item>
		<item id="1087" caption="ナビゲートロック">
			ナビゲートロックをONにした状態でウィンドウを開きます。
			ページ内のリンクをクリックした際に必ず新しいウィンドウでページを開きます。
			&quot;javascript:&quot;で始まるアドレスは開けません。メニューからナビゲートロックの
			チェックを外してください。
		</item>
		<item id="1118" caption="UserAgent">
			アクセスしたサーバーに送られるユーザー情報の一部を、ユーザーの任意の文字列に変更します。
			通常は変更の必要は無く、また変更すると表示出来なくなるページがあります。
		</item>
		<item id="1051" caption="ページを平面的に表示する">
			立体的な表示をやめ、スクロールバーを含むページを平面的に表示します。
			新しいウィンドウから適用されます。
		</item>
		<item id="1078" caption="ステータスバーをフィルターする">
			&quot;http&quot;, &quot;ftp&quot;, &quot;mailto&quot;, &quot;接続&quot;, &quot;file&quot;のいずれかの文字で始まる物だけがステータスバーに表示されます。
		</item>
		<item id="1108" caption="マウス・ジェスチャーを使用する">
			マウスジェスチャーを使用します。
		</item>
		<item id="1080" caption="mailto:無効">
			&quot;mailto:&quot;のリンクを無効にし、メールソフトが起動しないようにします。
		</item>
		<item id="1168" caption="ナビゲートロックされたページを閉じない">
			ナビゲートロックされたページをunDonutを終了される時以外は閉じないようにします。
			閉じる場合はナビゲートロックを解除してから閉じてください。
		</item>
	</dialog>

	<dialog id="207" description="ポップアップ抑止">
		<item id="1032" caption="ポップアップ抑止を有効にする">
			入力した文字列と開こうとするウィンドウのURLが一致した場合にウィンドウを開かないようにします。
			&quot;*&quot;や&quot;?&quot;はワイルドカードとして扱われるので、有効に指定することで部分的な一致でも適用できます。
			
			*＝すべての文字列を意味します。
			?＝一文字を意味します。
			hoge*＝hogeで始まる文字列
			*hoge＝hogeで終わる文字列
			*hoge*＝hogeを含む文字列
			ho*ge＝hoで始まりgeで終わる文字列
			hoge?＝hogeで始まる５文字
			hoge??＝hogeで始まる６文字
		</item>
		<item id="1000" caption="リスト">
			
		</item>
		<item id="1008" caption="エディット">
			登録する文字列を編集します。
		</item>
		<item id="1010" caption="追加">
			入力ボックスに入力した文字列を追加します。
		</item>
		<item id="1003" caption="削除">
			リストで選択した文字列を削除します。
		</item>
		<item id="1007" caption="すべて削除">
			リストの内容をすべて削除します。
		</item>
	</dialog>

	<dialog id="212" description="タイトル抑止">
		<item id="1334" caption="タイトル抑止を有効にする">
			入力した文字列とサイトのタイトルが一致した場合にウィンドウを開かないようにします。
			&quot;*&quot;や&quot;?&quot;はワイルドカードとして扱われるので、有効に指定することで部分的な一致でも適用できます。
			
			*＝すべての文字列を意味します。
			?＝一文字を意味します。
			hoge*＝hogeで始まる文字列
			*hoge＝hogeで終わる文字列
			*hoge*＝hogeを含む文字列
			ho*ge＝hoで始まりgeで終わる文字列
			hoge?＝hogeで始まる５文字
			hoge??＝hogeで始まる６文字
		</item>
		<item id="1000" caption="リスト">
			
		</item>
		<item id="1008" caption="エディット">
			登録する文字列を編集します。
		</item>
		<item id="1010" caption="追加">
			入力ボックスに入力した文字列を追加します。
		</item>
		<item id="1003" caption="削除">
			リストで選択した文字列を削除します。
		</item>
		<item id="1007" caption="すべて削除">
			リストの内容をすべて削除します。
		</item>
	</dialog>

	<dialog id="287" description="URL別セキュリティ">
		<item id="1335" caption="URL別セキュリティを有効にする">
			入力した文字列と開こうとするウィンドウのURLが一致した場合にセキュリティ・オプションを適応します。
			&quot;*&quot;や&quot;?&quot;はワイルドカードとして扱われるので、指定することで部分的な一致でも適用できます。
			（正規表現にチェックをした場合は、(perl等と同様の)正規表現が有効になります）

			*＝すべての文字列を意味します。
			?＝一文字を意味します。
			hoge*＝hogeで始まる文字列
			*hoge＝hogeで終わる文字列
			*hoge*＝hogeを含む文字列
			ho*ge＝hoで始まりgeで終わる文字列
			hoge?＝hogeで始まる５文字
			hoge??＝hogeで始まる６文字
		</item>
		<item id="1000" caption="リスト">
			
		</item>
		<item id="1327" caption="設定">
			セキュリティ・オプションやマルチメディア・オプション等の設定を行えます。
		</item>
		<item id="1010" caption="追加">
			入力ボックスに入力した文字列を追加します。
		</item>
		<item id="1003" caption="削除">
			リストで選択した文字列を削除します。
		</item>
		<item id="1007" caption="すべて削除">
			リストの内容をすべて削除します。
		</item>
	</dialog>

	<dialog id="224" description="関連づけ">
		<item id="1111" caption="リスト">
			unDonutで開くファイルを選択します。
			unDonutを通常使うブラウザ(標準のブラウザ)にしたい場合、すべてにチェックを入れてください。
			※すでに他のDonut系ブラウザで関連付けしていた場合すでにチェックが入っているので、
			　 そのまま関連づけのメニューの適用を押してください。
		</item>
	</dialog>

	<dialog id="226" description="確認ダイアログ">
		<item id="1113" caption="Donutを終了するとき">
			unDonutを終了する時に確認のダイアログを表示します。
		</item>
		<item id="1114" caption="すべて閉じるとき">
			すべてのウィンドウを閉じる（[ウィンドウ]-[すべて閉じる]）時に
			確認のダイアログを表示します。
		</item>
		<item id="1116" caption="これ以外を閉じるとき">
			アクティブなウィンドウ以外を閉じる（[ウィンドウ]-[これ以外を閉じる]）時に
			確認のダイアログを表示します。
		</item>
		<item id="1319" caption="このタブより左/右を閉じるとき">
			現在選択中のタブより左/右にあるタブをすべて閉じる
			（[ウィンドウ]-[このタブより左/右を閉じる]）時に
			確認のダイアログを表示します。
		</item>
		<item id="1237" caption="スクリプト機能を使用するとき">
			COMサーバーを使用したスクリプト機能を使用する時に
			確認のダイアログを表示します。
		</item>
	</dialog>

	<dialog id="228" description="プロキシ">
		<item id="1120" caption="プロキシ・リスト">
			使用するプロキシサーバーを”アドレス:ポート番号”として登録します。
			ローカルプロキシを使用する場合は”localhost:ポート番号”とします。
			unDonutの右下にあるプロキシのコンボボックス（表示欄）で選択すると
			インターネットオプションで設定したプロキシは無視され、unDonutで
			指定したプロキシが有効になります。
			※プロキシのメニューはコンボボックスを右クリックでも表示出来ます。
		</item>
		<item id="1122" caption="ランダムで使用する">
			一定時間ごとにプロキシを自動的に変更します。
		</item>
		<item id="1124" caption="分">
			プロキシを自動的に変更する時間を指定します。
		</item>
		<item id="1128" caption="秒">
			プロキシを自動的に変更する時間を指定します。
		</item>
		<item id="1130" caption="プロキシ非動作・リスト">
			プロキシを利用しないサイトを入力します。
		</item>
		<item id="1135" caption="ローカルには、プロキシを通さない">
			ローカルファイルを表示する場合にプロキシを利用しません。
		</item>
		<item id="1127" caption="プロキシは、ＩＥに任せる（再起動後有効）">
			インターネットオプションで設定されたプロキシを利用します。
			※チェックを入れるとDonutPで設定したプロキシは利用できなくなります。
		</item>
	</dialog>

	<dialog id="289" description="スキン">
		<item id="1224" caption="スキンフォルダ一覧">
			skinフォルダ内に対応したスキンを置くことで利用が可能になります。
		</item>
		<item id="1226" caption="説明">
			
		</item>
		<item id="1227" caption="現在のスキン">
			
		</item>
		<item id="1225" caption="適用">
			
		</item>
	</dialog>

	<dialog id="267" description="プラグイン">
		<item id="1286" caption="名称">
			
		</item>
		<item id="1290" caption="分類">
			
		</item>
		<item id="1287" caption="作者名">
			
		</item>
		<item id="1281" caption="URL">
			
		</item>
		<item id="1282" caption="E-Mail">
			
		</item>
		<item id="1283" caption="バージョン">
			
		</item>
		<item id="1284" caption="更新日">
			
		</item>
		<item id="1288" caption="設定">
			
		</item>
		<item id="1285" caption="説明">
			
		</item>
		<item id="1289" caption="リスト">
			プラグインによるunDonutの機能拡張を行います。
		</item>
	</dialog>


</option>
